// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.3.2.0
//      SpecFlow Generator Version:2.3.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace HowMuchToBorrowBDD.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.3.2.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("AllTestsHowMuchToBorrow", Description="As a prospective loan customer \r\nI want to use the home loan borrow calculator ", SourceFile="Features\\AllTestsHowMuchToBorrow.feature", SourceLine=0)]
    public partial class AllTestsHowMuchToBorrowFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "AllTestsHowMuchToBorrow.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "AllTestsHowMuchToBorrow", "As a prospective loan customer \r\nI want to use the home loan borrow calculator ", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 5
#line 6
testRunner.Given("I am on MuchBorrowCalculatorPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
        }
        
        public virtual void VerifyHomeLoanBorrowingPowerCalculator(string applicationType, string dependants, string propertyType, string yourIncome, string otherIncome, string livingExpenses, string otherLoanRepay, string otherCommitments, string creditCardLimits, string borrowResultAmount, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "VerifyBorrowResultAmount"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("VerifyHomeLoanBorrowingPowerCalculator", @__tags);
#line 9
this.ScenarioSetup(scenarioInfo);
#line 5
this.FeatureBackground();
#line 10
testRunner.Given(string.Format("I have entered Yourdetails {0} and {1} and {2} and {3} and {4} and {5} and {6} an" +
                        "d {7} and {8}", applicationType, dependants, propertyType, yourIncome, otherIncome, livingExpenses, otherLoanRepay, otherCommitments, creditCardLimits), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 11
testRunner.When("I click on Work out how much I could borrow button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 12
testRunner.Then(string.Format("the BorrowResult {0} will be displayed correctly", borrowResultAmount), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("VerifyHomeLoanBorrowingPowerCalculator, \'Single\'", new string[] {
                "VerifyBorrowResultAmount"}, SourceLine=14)]
        public virtual void VerifyHomeLoanBorrowingPowerCalculator_Single()
        {
#line 9
this.VerifyHomeLoanBorrowingPowerCalculator("\'Single\'", "\'0\'", "\'Home to live in\'", "\'80000\'", "\'10000\'", "\'500\'", "\'100\'", "\'0\'", "\'10000\'", "\'53200\'", ((string[])(null)));
#line hidden
        }
        
        public virtual void VerifyStartOverButton(string applicationType, string dependants, string propertyType, string yourIncome, string otherIncome, string livingExpenses, string otherLoanRepay, string otherCommitments, string creditCardLimits, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "VerifyStartOver"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("VerifyStartOverButton", @__tags);
#line 18
this.ScenarioSetup(scenarioInfo);
#line 5
this.FeatureBackground();
#line 19
testRunner.Given(string.Format("I have entered Yourdetails {0} and {1} and {2} and {3} and {4} and {5} and {6} an" +
                        "d {7} and {8}", applicationType, dependants, propertyType, yourIncome, otherIncome, livingExpenses, otherLoanRepay, otherCommitments, creditCardLimits), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 20
testRunner.And("I click on Work out how much I could borrow button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 21
testRunner.When("I click on StartOver Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 22
testRunner.Then("all the fields are reset to zero", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("VerifyStartOverButton, \'Single\'", new string[] {
                "VerifyStartOver"}, SourceLine=24)]
        public virtual void VerifyStartOverButton_Single()
        {
#line 18
this.VerifyStartOverButton("\'Single\'", "\'0\'", "\'Home to live in\'", "\'80000\'", "\'10000\'", "\'500\'", "\'100\'", "\'0\'", "\'10000\'", ((string[])(null)));
#line hidden
        }
        
        public virtual void VerifyErrorMessage(string applicationType, string dependants, string propertyType, string yourIncome, string otherIncome, string livingExpenses, string otherLoanRepay, string otherCommitments, string creditCardLimits, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "VerifyErrorMessage"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("VerifyErrorMessage", @__tags);
#line 28
this.ScenarioSetup(scenarioInfo);
#line 5
this.FeatureBackground();
#line 29
testRunner.Given(string.Format("I have entered Yourdetails {0} and {1} and {2} and {3} and {4} and {5} and {6} an" +
                        "d {7} and {8}", applicationType, dependants, propertyType, yourIncome, otherIncome, livingExpenses, otherLoanRepay, otherCommitments, creditCardLimits), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 30
testRunner.When("I click on Work out how much I could borrow button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 31
testRunner.Then("an appropriate error message will be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("VerifyErrorMessage, \'Single\'", new string[] {
                "VerifyErrorMessage"}, SourceLine=33)]
        public virtual void VerifyErrorMessage_Single()
        {
#line 28
this.VerifyErrorMessage("\'Single\'", "\'0\'", "\'Home to live in\'", "\'0\'", "\'0\'", "\'1\'", "\'0\'", "\'0\'", "\'0\'", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
